#!/bin/bash

CWD="$( pwd )"
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


users_choices () {
  read -p "We are going to use this python. Do you wish to continus? (Y/n): " choice
  if [ "$choice" == "Y" ] || [ "$choice" == "y" ]; then
    echo "yes"
  else
    echo "no"
  fi
}





cd $BASE_DIR

cd ./backend
rm -rf venv
python3 -m venv venv
source venv/bin/activate
which python

choice="$( users_choices )"
if [ "$choice" == "yes" ]; then
  echo "Installing..."
  python -m pip install pip -U
  pip install -r requirements.txt
  python manage.py migrate
  cp -r static_files ../client/dist
  echo "Done."
else
  echo "Aborting."
fi


cd $CWD


